"""Extract ticket theory text from tickets_raw.md → src/data/content/advertising_content.ts"""

import re
import os

with open("tickets_raw.md", "r", encoding="utf-8") as f:
    lines = f.readlines()

# ── Step 1: parse TOC to get known ticket numbers and title keywords ──────────
toc: dict[int, list[str]] = {}
toc_pattern = re.compile(r'\[(\d+)\.\s*(.+?)\]')

for line in lines[:220]:
    m = toc_pattern.search(line)
    if m:
        num = int(m.group(1))
        title = m.group(2).strip()
        # two meaningful words (>3 chars) for fuzzy matching
        words = [w for w in re.split(r'\W+', title) if len(w) > 3][:2]
        toc[num] = words

# Tickets absent from TOC — add manually
toc[34] = ["Консалтинговый", "процесс"]

print(f"TOC entries found: {sorted(toc.keys())}")

# ── Step 2: find content area start (first real ticket header) ────────────────
content_start = 0
for i, line in enumerate(lines):
    if re.match(r'^1\.\s+Происхождение', line):
        content_start = i
        break

print(f"Content starts at line {content_start + 1}")

# ── Step 3: locate start line of each ticket ──────────────────────────────────
# Match plain "N. Title", bold "**N. Title", or no-space "N.Title"
ticket_header_re = re.compile(r'^\*{0,2}(\d+)\.\s*(.*)')
ticket_starts: dict[int, int] = {}

for i, line in enumerate(lines[content_start:], start=content_start):
    m = ticket_header_re.match(line.rstrip())
    if not m:
        continue
    num = int(m.group(1))
    if num not in toc:
        continue
    if num in ticket_starts:  # first match only
        continue
    words = toc[num]
    if all(w.lower() in line.lower() for w in words):
        ticket_starts[num] = i
        print(f"  Found ticket {num} at line {i+1}: {line.rstrip()[:60]}")

print(f"Ticket headers located (pass 1): {sorted(ticket_starts.keys())}")
missing = [n for n in toc if n not in ticket_starts]

# ── Pass 2: title-text search for tickets with reset numbering ────────────────
if missing:
    print(f"Pass 2 – title search for: {missing}")
    # Build title-to-num lookup (first 6+ meaningful chars)
    title_frags: dict[str, int] = {}
    toc2_pattern = re.compile(r'\[(\d+)\.\s*(.+?)\]')
    for line in lines[:220]:
        m = toc2_pattern.search(line)
        if m:
            num = int(m.group(1))
            if num in missing:
                title = m.group(2).strip().lstrip('*').strip()
                # Use first 30 chars as a unique fragment
                frag = title[:35].lower()
                title_frags[frag] = num

    prefix_re = re.compile(r'^\*{0,2}\d*\.?\*{0,2}\s*')
    for i, line in enumerate(lines[content_start:], start=content_start):
        # Strip bold markers and any leading number
        stripped = prefix_re.sub('', line.strip()).strip().lstrip('*').strip()
        for frag, num in list(title_frags.items()):
            if num in ticket_starts:
                continue
            if stripped.lower().startswith(frag[:20]):
                ticket_starts[num] = i
                print(f"  [pass2] Found ticket {num} at line {i+1}: {line.rstrip()[:60]}")

missing = [n for n in toc if n not in ticket_starts]
if missing:
    print(f"WARNING – still not located: {missing}")

# ── Step 4: extract content blocks ───────────────────────────────────────────
sorted_nums = sorted(ticket_starts.keys())
contents: dict[int, str] = {}

base64_re = re.compile(r'!\[.*?\]\(data:image[^)]*\)')

for idx, num in enumerate(sorted_nums):
    start = ticket_starts[num]
    end = ticket_starts[sorted_nums[idx + 1]] if idx + 1 < len(sorted_nums) else len(lines)

    block = []
    for line in lines[start:end]:
        # Strip embedded base64 images (huge blobs)
        line = base64_re.sub('', line)
        # Skip lines that became empty after stripping
        if line.strip() == '![]()':
            continue
        block.append(line.rstrip())

    # Trim trailing blank lines
    while block and not block[-1].strip():
        block.pop()

    contents[num] = '\n'.join(block)

# ── Step 5: write TypeScript file ────────────────────────────────────────────
os.makedirs("src/data/content", exist_ok=True)
out_path = "src/data/content/advertising_content.ts"

ts = ["// Auto-generated by extract_content.py — do not edit manually",
      "export const advertisingContent: Record<number, string> = {"]

for num in sorted(contents.keys()):
    text = contents[num]
    # Escape for template literal
    text = text.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    ts.append(f"  {num}: `{text}`,\n")

ts.append("}")

with open(out_path, "w", encoding="utf-8") as f:
    f.write('\n'.join(ts))

total_chars = sum(len(v) for v in contents.values())
print(f"\nDone! {len(contents)} tickets → {out_path}")
print(f"Total content size: {total_chars:,} chars (~{total_chars // 1024} KB)")
for num in sorted(contents.keys())[:5]:
    print(f"  Ticket {num}: {len(contents[num]):,} chars")
